export type City = {
  name: string
  country: string
}

export const CITIES: City[] = [
  // United States
  { name: "New York", country: "US" },
  { name: "Los Angeles", country: "US" },
  { name: "Chicago", country: "US" },
  { name: "Houston", country: "US" },
  { name: "Phoenix", country: "US" },
  { name: "Philadelphia", country: "US" },
  { name: "San Antonio", country: "US" },
  { name: "San Diego", country: "US" },
  { name: "Dallas", country: "US" },
  { name: "San Jose", country: "US" },
  { name: "Austin", country: "US" },
  { name: "Jacksonville", country: "US" },
  { name: "San Francisco", country: "US" },
  { name: "Seattle", country: "US" },
  { name: "Denver", country: "US" },
  { name: "Washington D.C.", country: "US" },
  { name: "Nashville", country: "US" },
  { name: "Boston", country: "US" },
  { name: "Portland", country: "US" },
  { name: "Las Vegas", country: "US" },
  { name: "Atlanta", country: "US" },
  { name: "Miami", country: "US" },
  { name: "Minneapolis", country: "US" },
  { name: "Detroit", country: "US" },
  { name: "Honolulu", country: "US" },
  { name: "Anchorage", country: "US" },
  // Canada
  { name: "Toronto", country: "CA" },
  { name: "Montreal", country: "CA" },
  { name: "Vancouver", country: "CA" },
  { name: "Calgary", country: "CA" },
  { name: "Edmonton", country: "CA" },
  { name: "Ottawa", country: "CA" },
  { name: "Winnipeg", country: "CA" },
  { name: "Halifax", country: "CA" },
  // Mexico
  { name: "Mexico City", country: "MX" },
  { name: "Guadalajara", country: "MX" },
  { name: "Monterrey", country: "MX" },
  { name: "Cancún", country: "MX" },
  { name: "Puebla", country: "MX" },
  // Brazil
  { name: "São Paulo", country: "BR" },
  { name: "Rio de Janeiro", country: "BR" },
  { name: "Brasília", country: "BR" },
  { name: "Salvador", country: "BR" },
  { name: "Recife", country: "BR" },
  { name: "Curitiba", country: "BR" },
  // Argentina
  { name: "Buenos Aires", country: "AR" },
  { name: "Córdoba", country: "AR" },
  { name: "Rosario", country: "AR" },
  // Colombia
  { name: "Bogotá", country: "CO" },
  { name: "Medellín", country: "CO" },
  { name: "Cali", country: "CO" },
  // Chile
  { name: "Santiago", country: "CL" },
  { name: "Valparaíso", country: "CL" },
  // Peru
  { name: "Lima", country: "PE" },
  // Venezuela
  { name: "Caracas", country: "VE" },
  // Ecuador
  { name: "Quito", country: "EC" },
  { name: "Guayaquil", country: "EC" },
  // Uruguay
  { name: "Montevideo", country: "UY" },
  // Paraguay
  { name: "Asunción", country: "PY" },
  // Bolivia
  { name: "La Paz", country: "BO" },
  // Central America & Caribbean
  { name: "Panama City", country: "PA" },
  { name: "San José", country: "CR" },
  { name: "Guatemala City", country: "GT" },
  { name: "Havana", country: "CU" },
  { name: "Santo Domingo", country: "DO" },
  { name: "Kingston", country: "JM" },
  { name: "San Salvador", country: "SV" },
  { name: "Tegucigalpa", country: "HN" },
  { name: "Managua", country: "NI" },
  // United Kingdom
  { name: "London", country: "GB" },
  { name: "Manchester", country: "GB" },
  { name: "Birmingham", country: "GB" },
  { name: "Edinburgh", country: "GB" },
  { name: "Glasgow", country: "GB" },
  { name: "Liverpool", country: "GB" },
  { name: "Bristol", country: "GB" },
  { name: "Leeds", country: "GB" },
  // Ireland
  { name: "Dublin", country: "IE" },
  { name: "Cork", country: "IE" },
  // France
  { name: "Paris", country: "FR" },
  { name: "Lyon", country: "FR" },
  { name: "Marseille", country: "FR" },
  { name: "Toulouse", country: "FR" },
  { name: "Nice", country: "FR" },
  // Germany
  { name: "Berlin", country: "DE" },
  { name: "Munich", country: "DE" },
  { name: "Hamburg", country: "DE" },
  { name: "Frankfurt", country: "DE" },
  { name: "Cologne", country: "DE" },
  { name: "Stuttgart", country: "DE" },
  // Spain
  { name: "Madrid", country: "ES" },
  { name: "Barcelona", country: "ES" },
  { name: "Valencia", country: "ES" },
  { name: "Seville", country: "ES" },
  // Italy
  { name: "Rome", country: "IT" },
  { name: "Milan", country: "IT" },
  { name: "Naples", country: "IT" },
  { name: "Turin", country: "IT" },
  { name: "Florence", country: "IT" },
  // Portugal
  { name: "Lisbon", country: "PT" },
  { name: "Porto", country: "PT" },
  // Netherlands
  { name: "Amsterdam", country: "NL" },
  { name: "Rotterdam", country: "NL" },
  { name: "The Hague", country: "NL" },
  // Belgium
  { name: "Brussels", country: "BE" },
  { name: "Antwerp", country: "BE" },
  // Switzerland
  { name: "Zurich", country: "CH" },
  { name: "Geneva", country: "CH" },
  { name: "Bern", country: "CH" },
  // Austria
  { name: "Vienna", country: "AT" },
  { name: "Salzburg", country: "AT" },
  // Nordics
  { name: "Stockholm", country: "SE" },
  { name: "Gothenburg", country: "SE" },
  { name: "Oslo", country: "NO" },
  { name: "Bergen", country: "NO" },
  { name: "Copenhagen", country: "DK" },
  { name: "Helsinki", country: "FI" },
  { name: "Reykjavik", country: "IS" },
  // Eastern Europe
  { name: "Warsaw", country: "PL" },
  { name: "Kraków", country: "PL" },
  { name: "Prague", country: "CZ" },
  { name: "Budapest", country: "HU" },
  { name: "Bucharest", country: "RO" },
  { name: "Sofia", country: "BG" },
  { name: "Belgrade", country: "RS" },
  { name: "Zagreb", country: "HR" },
  { name: "Ljubljana", country: "SI" },
  { name: "Bratislava", country: "SK" },
  { name: "Tallinn", country: "EE" },
  { name: "Riga", country: "LV" },
  { name: "Vilnius", country: "LT" },
  { name: "Kyiv", country: "UA" },
  { name: "Minsk", country: "BY" },
  { name: "Moscow", country: "RU" },
  { name: "Saint Petersburg", country: "RU" },
  // Greece & Cyprus
  { name: "Athens", country: "GR" },
  { name: "Thessaloniki", country: "GR" },
  { name: "Nicosia", country: "CY" },
  // Turkey
  { name: "Istanbul", country: "TR" },
  { name: "Ankara", country: "TR" },
  { name: "Izmir", country: "TR" },
  // Middle East
  { name: "Dubai", country: "AE" },
  { name: "Abu Dhabi", country: "AE" },
  { name: "Riyadh", country: "SA" },
  { name: "Jeddah", country: "SA" },
  { name: "Doha", country: "QA" },
  { name: "Kuwait City", country: "KW" },
  { name: "Manama", country: "BH" },
  { name: "Muscat", country: "OM" },
  { name: "Amman", country: "JO" },
  { name: "Beirut", country: "LB" },
  { name: "Baghdad", country: "IQ" },
  { name: "Tehran", country: "IR" },
  { name: "Jerusalem", country: "IL" },
  { name: "Tel Aviv", country: "IL" },
  { name: "Damascus", country: "SY" },
  // South Asia
  { name: "Delhi", country: "IN" },
  { name: "Mumbai", country: "IN" },
  { name: "Bangalore", country: "IN" },
  { name: "Chennai", country: "IN" },
  { name: "Kolkata", country: "IN" },
  { name: "Hyderabad", country: "IN" },
  { name: "Pune", country: "IN" },
  { name: "Ahmedabad", country: "IN" },
  { name: "Dhaka", country: "BD" },
  { name: "Karachi", country: "PK" },
  { name: "Lahore", country: "PK" },
  { name: "Islamabad", country: "PK" },
  { name: "Colombo", country: "LK" },
  { name: "Kathmandu", country: "NP" },
  { name: "Kabul", country: "AF" },
  // Southeast Asia
  { name: "Bangkok", country: "TH" },
  { name: "Singapore", country: "SG" },
  { name: "Kuala Lumpur", country: "MY" },
  { name: "Jakarta", country: "ID" },
  { name: "Bali", country: "ID" },
  { name: "Manila", country: "PH" },
  { name: "Ho Chi Minh City", country: "VN" },
  { name: "Hanoi", country: "VN" },
  { name: "Phnom Penh", country: "KH" },
  { name: "Yangon", country: "MM" },
  // East Asia
  { name: "Tokyo", country: "JP" },
  { name: "Osaka", country: "JP" },
  { name: "Kyoto", country: "JP" },
  { name: "Seoul", country: "KR" },
  { name: "Busan", country: "KR" },
  { name: "Beijing", country: "CN" },
  { name: "Shanghai", country: "CN" },
  { name: "Guangzhou", country: "CN" },
  { name: "Shenzhen", country: "CN" },
  { name: "Hong Kong", country: "CN" },
  { name: "Taipei", country: "TW" },
  { name: "Ulaanbaatar", country: "MN" },
  // Central Asia
  { name: "Almaty", country: "KZ" },
  { name: "Tashkent", country: "UZ" },
  { name: "Bishkek", country: "KG" },
  { name: "Tbilisi", country: "GE" },
  { name: "Yerevan", country: "AM" },
  { name: "Baku", country: "AZ" },
  // Australia & New Zealand
  { name: "Sydney", country: "AU" },
  { name: "Melbourne", country: "AU" },
  { name: "Brisbane", country: "AU" },
  { name: "Perth", country: "AU" },
  { name: "Adelaide", country: "AU" },
  { name: "Auckland", country: "NZ" },
  { name: "Wellington", country: "NZ" },
  { name: "Christchurch", country: "NZ" },
  // Africa - North
  { name: "Cairo", country: "EG" },
  { name: "Alexandria", country: "EG" },
  { name: "Casablanca", country: "MA" },
  { name: "Rabat", country: "MA" },
  { name: "Tunis", country: "TN" },
  { name: "Algiers", country: "DZ" },
  { name: "Tripoli", country: "LY" },
  // Africa - West
  { name: "Lagos", country: "NG" },
  { name: "Abuja", country: "NG" },
  { name: "Accra", country: "GH" },
  { name: "Dakar", country: "SN" },
  { name: "Abidjan", country: "CI" },
  { name: "Douala", country: "CM" },
  // Africa - East
  { name: "Nairobi", country: "KE" },
  { name: "Mombasa", country: "KE" },
  { name: "Addis Ababa", country: "ET" },
  { name: "Dar es Salaam", country: "TZ" },
  { name: "Kampala", country: "UG" },
  { name: "Kigali", country: "RW" },
  // Africa - South
  { name: "Johannesburg", country: "ZA" },
  { name: "Cape Town", country: "ZA" },
  { name: "Durban", country: "ZA" },
  { name: "Pretoria", country: "ZA" },
  { name: "Windhoek", country: "NA" },
  { name: "Lusaka", country: "ZM" },
  { name: "Harare", country: "ZW" },
  { name: "Maputo", country: "MZ" },
]

export function getCitiesByCountry(countryCode: string): City[] {
  return CITIES.filter((c) => c.country === countryCode)
}
