type TimezoneLocation = {
  country: string
  city: string
}

const TIMEZONE_MAP: Record<string, TimezoneLocation> = {
  // Africa
  "Africa/Abidjan": { country: "CI", city: "Abidjan" },
  "Africa/Accra": { country: "GH", city: "Accra" },
  "Africa/Addis_Ababa": { country: "ET", city: "Addis Ababa" },
  "Africa/Algiers": { country: "DZ", city: "Algiers" },
  "Africa/Cairo": { country: "EG", city: "Cairo" },
  "Africa/Casablanca": { country: "MA", city: "Casablanca" },
  "Africa/Dakar": { country: "SN", city: "Dakar" },
  "Africa/Dar_es_Salaam": { country: "TZ", city: "Dar es Salaam" },
  "Africa/Douala": { country: "CM", city: "Douala" },
  "Africa/Harare": { country: "ZW", city: "Harare" },
  "Africa/Johannesburg": { country: "ZA", city: "Johannesburg" },
  "Africa/Kampala": { country: "UG", city: "Kampala" },
  "Africa/Khartoum": { country: "SD", city: "Khartoum" },
  "Africa/Kigali": { country: "RW", city: "Kigali" },
  "Africa/Kinshasa": { country: "CD", city: "Kinshasa" },
  "Africa/Lagos": { country: "NG", city: "Lagos" },
  "Africa/Lusaka": { country: "ZM", city: "Lusaka" },
  "Africa/Maputo": { country: "MZ", city: "Maputo" },
  "Africa/Nairobi": { country: "KE", city: "Nairobi" },
  "Africa/Tripoli": { country: "LY", city: "Tripoli" },
  "Africa/Tunis": { country: "TN", city: "Tunis" },
  "Africa/Windhoek": { country: "NA", city: "Windhoek" },
  // Americas
  "America/Anchorage": { country: "US", city: "Anchorage" },
  "America/Argentina/Buenos_Aires": { country: "AR", city: "Buenos Aires" },
  "America/Bogota": { country: "CO", city: "Bogotá" },
  "America/Buenos_Aires": { country: "AR", city: "Buenos Aires" },
  "America/Caracas": { country: "VE", city: "Caracas" },
  "America/Chicago": { country: "US", city: "Chicago" },
  "America/Denver": { country: "US", city: "Denver" },
  "America/Edmonton": { country: "CA", city: "Edmonton" },
  "America/Guatemala": { country: "GT", city: "Guatemala City" },
  "America/Guayaquil": { country: "EC", city: "Guayaquil" },
  "America/Halifax": { country: "CA", city: "Halifax" },
  "America/Havana": { country: "CU", city: "Havana" },
  "America/La_Paz": { country: "BO", city: "La Paz" },
  "America/Lima": { country: "PE", city: "Lima" },
  "America/Los_Angeles": { country: "US", city: "Los Angeles" },
  "America/Mexico_City": { country: "MX", city: "Mexico City" },
  "America/Monterrey": { country: "MX", city: "Monterrey" },
  "America/Montevideo": { country: "UY", city: "Montevideo" },
  "America/Montreal": { country: "CA", city: "Montreal" },
  "America/New_York": { country: "US", city: "New York" },
  "America/Panama": { country: "PA", city: "Panama City" },
  "America/Phoenix": { country: "US", city: "Phoenix" },
  "America/Santiago": { country: "CL", city: "Santiago" },
  "America/Santo_Domingo": { country: "DO", city: "Santo Domingo" },
  "America/Sao_Paulo": { country: "BR", city: "São Paulo" },
  "America/Toronto": { country: "CA", city: "Toronto" },
  "America/Vancouver": { country: "CA", city: "Vancouver" },
  "America/Winnipeg": { country: "CA", city: "Winnipeg" },
  // Asia
  "Asia/Almaty": { country: "KZ", city: "Almaty" },
  "Asia/Amman": { country: "JO", city: "Amman" },
  "Asia/Baghdad": { country: "IQ", city: "Baghdad" },
  "Asia/Baku": { country: "AZ", city: "Baku" },
  "Asia/Bangkok": { country: "TH", city: "Bangkok" },
  "Asia/Beirut": { country: "LB", city: "Beirut" },
  "Asia/Colombo": { country: "LK", city: "Colombo" },
  "Asia/Damascus": { country: "SY", city: "Damascus" },
  "Asia/Dhaka": { country: "BD", city: "Dhaka" },
  "Asia/Dubai": { country: "AE", city: "Dubai" },
  "Asia/Ho_Chi_Minh": { country: "VN", city: "Ho Chi Minh City" },
  "Asia/Hong_Kong": { country: "CN", city: "Hong Kong" },
  "Asia/Istanbul": { country: "TR", city: "Istanbul" },
  "Asia/Jakarta": { country: "ID", city: "Jakarta" },
  "Asia/Jerusalem": { country: "IL", city: "Jerusalem" },
  "Asia/Kabul": { country: "AF", city: "Kabul" },
  "Asia/Karachi": { country: "PK", city: "Karachi" },
  "Asia/Kathmandu": { country: "NP", city: "Kathmandu" },
  "Asia/Kolkata": { country: "IN", city: "Delhi" },
  "Asia/Kuala_Lumpur": { country: "MY", city: "Kuala Lumpur" },
  "Asia/Kuwait": { country: "KW", city: "Kuwait City" },
  "Asia/Manila": { country: "PH", city: "Manila" },
  "Asia/Muscat": { country: "OM", city: "Muscat" },
  "Asia/Qatar": { country: "QA", city: "Doha" },
  "Asia/Riyadh": { country: "SA", city: "Riyadh" },
  "Asia/Seoul": { country: "KR", city: "Seoul" },
  "Asia/Shanghai": { country: "CN", city: "Shanghai" },
  "Asia/Singapore": { country: "SG", city: "Singapore" },
  "Asia/Taipei": { country: "TW", city: "Taipei" },
  "Asia/Tashkent": { country: "UZ", city: "Tashkent" },
  "Asia/Tbilisi": { country: "GE", city: "Tbilisi" },
  "Asia/Tehran": { country: "IR", city: "Tehran" },
  "Asia/Tokyo": { country: "JP", city: "Tokyo" },
  "Asia/Ulaanbaatar": { country: "MN", city: "Ulaanbaatar" },
  "Asia/Yangon": { country: "MM", city: "Yangon" },
  "Asia/Yerevan": { country: "AM", city: "Yerevan" },
  // Australia & Pacific
  "Australia/Adelaide": { country: "AU", city: "Adelaide" },
  "Australia/Brisbane": { country: "AU", city: "Brisbane" },
  "Australia/Melbourne": { country: "AU", city: "Melbourne" },
  "Australia/Perth": { country: "AU", city: "Perth" },
  "Australia/Sydney": { country: "AU", city: "Sydney" },
  "Pacific/Auckland": { country: "NZ", city: "Auckland" },
  "Pacific/Honolulu": { country: "US", city: "Honolulu" },
  // Europe
  "Europe/Amsterdam": { country: "NL", city: "Amsterdam" },
  "Europe/Athens": { country: "GR", city: "Athens" },
  "Europe/Belgrade": { country: "RS", city: "Belgrade" },
  "Europe/Berlin": { country: "DE", city: "Berlin" },
  "Europe/Bratislava": { country: "SK", city: "Bratislava" },
  "Europe/Brussels": { country: "BE", city: "Brussels" },
  "Europe/Bucharest": { country: "RO", city: "Bucharest" },
  "Europe/Budapest": { country: "HU", city: "Budapest" },
  "Europe/Copenhagen": { country: "DK", city: "Copenhagen" },
  "Europe/Dublin": { country: "IE", city: "Dublin" },
  "Europe/Helsinki": { country: "FI", city: "Helsinki" },
  "Europe/Istanbul": { country: "TR", city: "Istanbul" },
  "Europe/Kyiv": { country: "UA", city: "Kyiv" },
  "Europe/Lisbon": { country: "PT", city: "Lisbon" },
  "Europe/Ljubljana": { country: "SI", city: "Ljubljana" },
  "Europe/London": { country: "GB", city: "London" },
  "Europe/Madrid": { country: "ES", city: "Madrid" },
  "Europe/Minsk": { country: "BY", city: "Minsk" },
  "Europe/Moscow": { country: "RU", city: "Moscow" },
  "Europe/Oslo": { country: "NO", city: "Oslo" },
  "Europe/Paris": { country: "FR", city: "Paris" },
  "Europe/Prague": { country: "CZ", city: "Prague" },
  "Europe/Riga": { country: "LV", city: "Riga" },
  "Europe/Rome": { country: "IT", city: "Rome" },
  "Europe/Sofia": { country: "BG", city: "Sofia" },
  "Europe/Stockholm": { country: "SE", city: "Stockholm" },
  "Europe/Tallinn": { country: "EE", city: "Tallinn" },
  "Europe/Vienna": { country: "AT", city: "Vienna" },
  "Europe/Vilnius": { country: "LT", city: "Vilnius" },
  "Europe/Warsaw": { country: "PL", city: "Warsaw" },
  "Europe/Zagreb": { country: "HR", city: "Zagreb" },
  "Europe/Zurich": { country: "CH", city: "Zurich" },
  // Aliases
  "Atlantic/Reykjavik": { country: "IS", city: "Reykjavik" },
  "US/Eastern": { country: "US", city: "New York" },
  "US/Central": { country: "US", city: "Chicago" },
  "US/Mountain": { country: "US", city: "Denver" },
  "US/Pacific": { country: "US", city: "Los Angeles" },
  "US/Alaska": { country: "US", city: "Anchorage" },
  "US/Hawaii": { country: "US", city: "Honolulu" },
  "Canada/Eastern": { country: "CA", city: "Toronto" },
  "Canada/Pacific": { country: "CA", city: "Vancouver" },
}

const FALLBACK: TimezoneLocation = { country: "", city: "" }

export function detectLocationFromTimezone(timezone: string): TimezoneLocation {
  return TIMEZONE_MAP[timezone] ?? FALLBACK
}
