/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardInvitationsRouteImport } from './routes/dashboard/invitations'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as UsernameGroupSlugIndexRouteImport } from './routes/$username.$groupSlug/index'
import { Route as DashboardOrgOrgIdRouteImport } from './routes/dashboard/org.$orgId'
import { Route as DashboardGroupsCreateRouteImport } from './routes/dashboard/groups/create'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardOrgOrgIdIndexRouteImport } from './routes/dashboard/org.$orgId/index'
import { Route as DashboardOrgOrgIdSettingsRouteImport } from './routes/dashboard/org.$orgId/settings'
import { Route as DashboardOrgOrgIdProfileRouteImport } from './routes/dashboard/org.$orgId/profile'
import { Route as DashboardOrgOrgIdMembersRouteImport } from './routes/dashboard/org.$orgId/members'
import { Route as DashboardOrgOrgIdJoinRequestsRouteImport } from './routes/dashboard/org.$orgId/join-requests'
import { Route as DashboardOrgOrgIdInvitationsRouteImport } from './routes/dashboard/org.$orgId/invitations'
import { Route as DashboardOrgOrgIdSessionsIndexRouteImport } from './routes/dashboard/org.$orgId/sessions/index'
import { Route as DashboardOrgOrgIdSessionsCreateRouteImport } from './routes/dashboard/org.$orgId/sessions/create'
import { Route as DashboardOrgOrgIdSessionsSessionIdRouteImport } from './routes/dashboard/org.$orgId/sessions/$sessionId'
import { Route as DashboardOrgOrgIdSessionsSessionIdIndexRouteImport } from './routes/dashboard/org.$orgId/sessions/$sessionId/index'
import { Route as DashboardOrgOrgIdSessionsSessionIdRosterRouteImport } from './routes/dashboard/org.$orgId/sessions/$sessionId/roster'
import { Route as DashboardOrgOrgIdSessionsSessionIdEditRouteImport } from './routes/dashboard/org.$orgId/sessions/$sessionId/edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitationsRoute = DashboardInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameGroupSlugIndexRoute = UsernameGroupSlugIndexRouteImport.update({
  id: '/$username/$groupSlug/',
  path: '/$username/$groupSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgOrgIdRoute = DashboardOrgOrgIdRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsCreateRoute = DashboardGroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgOrgIdIndexRoute = DashboardOrgOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardOrgOrgIdRoute,
} as any)
const DashboardOrgOrgIdSettingsRoute =
  DashboardOrgOrgIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardOrgOrgIdRoute,
  } as any)
const DashboardOrgOrgIdProfileRoute =
  DashboardOrgOrgIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardOrgOrgIdRoute,
  } as any)
const DashboardOrgOrgIdMembersRoute =
  DashboardOrgOrgIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => DashboardOrgOrgIdRoute,
  } as any)
const DashboardOrgOrgIdJoinRequestsRoute =
  DashboardOrgOrgIdJoinRequestsRouteImport.update({
    id: '/join-requests',
    path: '/join-requests',
    getParentRoute: () => DashboardOrgOrgIdRoute,
  } as any)
const DashboardOrgOrgIdInvitationsRoute =
  DashboardOrgOrgIdInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => DashboardOrgOrgIdRoute,
  } as any)
const DashboardOrgOrgIdSessionsIndexRoute =
  DashboardOrgOrgIdSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => DashboardOrgOrgIdRoute,
  } as any)
const DashboardOrgOrgIdSessionsCreateRoute =
  DashboardOrgOrgIdSessionsCreateRouteImport.update({
    id: '/sessions/create',
    path: '/sessions/create',
    getParentRoute: () => DashboardOrgOrgIdRoute,
  } as any)
const DashboardOrgOrgIdSessionsSessionIdRoute =
  DashboardOrgOrgIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => DashboardOrgOrgIdRoute,
  } as any)
const DashboardOrgOrgIdSessionsSessionIdIndexRoute =
  DashboardOrgOrgIdSessionsSessionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrgOrgIdSessionsSessionIdRoute,
  } as any)
const DashboardOrgOrgIdSessionsSessionIdRosterRoute =
  DashboardOrgOrgIdSessionsSessionIdRosterRouteImport.update({
    id: '/roster',
    path: '/roster',
    getParentRoute: () => DashboardOrgOrgIdSessionsSessionIdRoute,
  } as any)
const DashboardOrgOrgIdSessionsSessionIdEditRoute =
  DashboardOrgOrgIdSessionsSessionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardOrgOrgIdSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/groups/create': typeof DashboardGroupsCreateRoute
  '/dashboard/org/$orgId': typeof DashboardOrgOrgIdRouteWithChildren
  '/$username/$groupSlug/': typeof UsernameGroupSlugIndexRoute
  '/dashboard/org/$orgId/invitations': typeof DashboardOrgOrgIdInvitationsRoute
  '/dashboard/org/$orgId/join-requests': typeof DashboardOrgOrgIdJoinRequestsRoute
  '/dashboard/org/$orgId/members': typeof DashboardOrgOrgIdMembersRoute
  '/dashboard/org/$orgId/profile': typeof DashboardOrgOrgIdProfileRoute
  '/dashboard/org/$orgId/settings': typeof DashboardOrgOrgIdSettingsRoute
  '/dashboard/org/$orgId/': typeof DashboardOrgOrgIdIndexRoute
  '/dashboard/org/$orgId/sessions/$sessionId': typeof DashboardOrgOrgIdSessionsSessionIdRouteWithChildren
  '/dashboard/org/$orgId/sessions/create': typeof DashboardOrgOrgIdSessionsCreateRoute
  '/dashboard/org/$orgId/sessions/': typeof DashboardOrgOrgIdSessionsIndexRoute
  '/dashboard/org/$orgId/sessions/$sessionId/edit': typeof DashboardOrgOrgIdSessionsSessionIdEditRoute
  '/dashboard/org/$orgId/sessions/$sessionId/roster': typeof DashboardOrgOrgIdSessionsSessionIdRosterRoute
  '/dashboard/org/$orgId/sessions/$sessionId/': typeof DashboardOrgOrgIdSessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/groups/create': typeof DashboardGroupsCreateRoute
  '/$username/$groupSlug': typeof UsernameGroupSlugIndexRoute
  '/dashboard/org/$orgId/invitations': typeof DashboardOrgOrgIdInvitationsRoute
  '/dashboard/org/$orgId/join-requests': typeof DashboardOrgOrgIdJoinRequestsRoute
  '/dashboard/org/$orgId/members': typeof DashboardOrgOrgIdMembersRoute
  '/dashboard/org/$orgId/profile': typeof DashboardOrgOrgIdProfileRoute
  '/dashboard/org/$orgId/settings': typeof DashboardOrgOrgIdSettingsRoute
  '/dashboard/org/$orgId': typeof DashboardOrgOrgIdIndexRoute
  '/dashboard/org/$orgId/sessions/create': typeof DashboardOrgOrgIdSessionsCreateRoute
  '/dashboard/org/$orgId/sessions': typeof DashboardOrgOrgIdSessionsIndexRoute
  '/dashboard/org/$orgId/sessions/$sessionId/edit': typeof DashboardOrgOrgIdSessionsSessionIdEditRoute
  '/dashboard/org/$orgId/sessions/$sessionId/roster': typeof DashboardOrgOrgIdSessionsSessionIdRosterRoute
  '/dashboard/org/$orgId/sessions/$sessionId': typeof DashboardOrgOrgIdSessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/groups/create': typeof DashboardGroupsCreateRoute
  '/dashboard/org/$orgId': typeof DashboardOrgOrgIdRouteWithChildren
  '/$username/$groupSlug/': typeof UsernameGroupSlugIndexRoute
  '/dashboard/org/$orgId/invitations': typeof DashboardOrgOrgIdInvitationsRoute
  '/dashboard/org/$orgId/join-requests': typeof DashboardOrgOrgIdJoinRequestsRoute
  '/dashboard/org/$orgId/members': typeof DashboardOrgOrgIdMembersRoute
  '/dashboard/org/$orgId/profile': typeof DashboardOrgOrgIdProfileRoute
  '/dashboard/org/$orgId/settings': typeof DashboardOrgOrgIdSettingsRoute
  '/dashboard/org/$orgId/': typeof DashboardOrgOrgIdIndexRoute
  '/dashboard/org/$orgId/sessions/$sessionId': typeof DashboardOrgOrgIdSessionsSessionIdRouteWithChildren
  '/dashboard/org/$orgId/sessions/create': typeof DashboardOrgOrgIdSessionsCreateRoute
  '/dashboard/org/$orgId/sessions/': typeof DashboardOrgOrgIdSessionsIndexRoute
  '/dashboard/org/$orgId/sessions/$sessionId/edit': typeof DashboardOrgOrgIdSessionsSessionIdEditRoute
  '/dashboard/org/$orgId/sessions/$sessionId/roster': typeof DashboardOrgOrgIdSessionsSessionIdRosterRoute
  '/dashboard/org/$orgId/sessions/$sessionId/': typeof DashboardOrgOrgIdSessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/health'
    | '/dashboard/invitations'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/groups/create'
    | '/dashboard/org/$orgId'
    | '/$username/$groupSlug/'
    | '/dashboard/org/$orgId/invitations'
    | '/dashboard/org/$orgId/join-requests'
    | '/dashboard/org/$orgId/members'
    | '/dashboard/org/$orgId/profile'
    | '/dashboard/org/$orgId/settings'
    | '/dashboard/org/$orgId/'
    | '/dashboard/org/$orgId/sessions/$sessionId'
    | '/dashboard/org/$orgId/sessions/create'
    | '/dashboard/org/$orgId/sessions/'
    | '/dashboard/org/$orgId/sessions/$sessionId/edit'
    | '/dashboard/org/$orgId/sessions/$sessionId/roster'
    | '/dashboard/org/$orgId/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/health'
    | '/dashboard/invitations'
    | '/dashboard/profile'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/groups/create'
    | '/$username/$groupSlug'
    | '/dashboard/org/$orgId/invitations'
    | '/dashboard/org/$orgId/join-requests'
    | '/dashboard/org/$orgId/members'
    | '/dashboard/org/$orgId/profile'
    | '/dashboard/org/$orgId/settings'
    | '/dashboard/org/$orgId'
    | '/dashboard/org/$orgId/sessions/create'
    | '/dashboard/org/$orgId/sessions'
    | '/dashboard/org/$orgId/sessions/$sessionId/edit'
    | '/dashboard/org/$orgId/sessions/$sessionId/roster'
    | '/dashboard/org/$orgId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/api/health'
    | '/dashboard/invitations'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/groups/create'
    | '/dashboard/org/$orgId'
    | '/$username/$groupSlug/'
    | '/dashboard/org/$orgId/invitations'
    | '/dashboard/org/$orgId/join-requests'
    | '/dashboard/org/$orgId/members'
    | '/dashboard/org/$orgId/profile'
    | '/dashboard/org/$orgId/settings'
    | '/dashboard/org/$orgId/'
    | '/dashboard/org/$orgId/sessions/$sessionId'
    | '/dashboard/org/$orgId/sessions/create'
    | '/dashboard/org/$orgId/sessions/'
    | '/dashboard/org/$orgId/sessions/$sessionId/edit'
    | '/dashboard/org/$orgId/sessions/$sessionId/roster'
    | '/dashboard/org/$orgId/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  UsernameGroupSlugIndexRoute: typeof UsernameGroupSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invitations': {
      id: '/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof DashboardInvitationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$groupSlug/': {
      id: '/$username/$groupSlug/'
      path: '/$username/$groupSlug'
      fullPath: '/$username/$groupSlug/'
      preLoaderRoute: typeof UsernameGroupSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/org/$orgId': {
      id: '/dashboard/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/dashboard/org/$orgId'
      preLoaderRoute: typeof DashboardOrgOrgIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups/create': {
      id: '/dashboard/groups/create'
      path: '/groups/create'
      fullPath: '/dashboard/groups/create'
      preLoaderRoute: typeof DashboardGroupsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/org/$orgId/': {
      id: '/dashboard/org/$orgId/'
      path: '/'
      fullPath: '/dashboard/org/$orgId/'
      preLoaderRoute: typeof DashboardOrgOrgIdIndexRouteImport
      parentRoute: typeof DashboardOrgOrgIdRoute
    }
    '/dashboard/org/$orgId/settings': {
      id: '/dashboard/org/$orgId/settings'
      path: '/settings'
      fullPath: '/dashboard/org/$orgId/settings'
      preLoaderRoute: typeof DashboardOrgOrgIdSettingsRouteImport
      parentRoute: typeof DashboardOrgOrgIdRoute
    }
    '/dashboard/org/$orgId/profile': {
      id: '/dashboard/org/$orgId/profile'
      path: '/profile'
      fullPath: '/dashboard/org/$orgId/profile'
      preLoaderRoute: typeof DashboardOrgOrgIdProfileRouteImport
      parentRoute: typeof DashboardOrgOrgIdRoute
    }
    '/dashboard/org/$orgId/members': {
      id: '/dashboard/org/$orgId/members'
      path: '/members'
      fullPath: '/dashboard/org/$orgId/members'
      preLoaderRoute: typeof DashboardOrgOrgIdMembersRouteImport
      parentRoute: typeof DashboardOrgOrgIdRoute
    }
    '/dashboard/org/$orgId/join-requests': {
      id: '/dashboard/org/$orgId/join-requests'
      path: '/join-requests'
      fullPath: '/dashboard/org/$orgId/join-requests'
      preLoaderRoute: typeof DashboardOrgOrgIdJoinRequestsRouteImport
      parentRoute: typeof DashboardOrgOrgIdRoute
    }
    '/dashboard/org/$orgId/invitations': {
      id: '/dashboard/org/$orgId/invitations'
      path: '/invitations'
      fullPath: '/dashboard/org/$orgId/invitations'
      preLoaderRoute: typeof DashboardOrgOrgIdInvitationsRouteImport
      parentRoute: typeof DashboardOrgOrgIdRoute
    }
    '/dashboard/org/$orgId/sessions/': {
      id: '/dashboard/org/$orgId/sessions/'
      path: '/sessions'
      fullPath: '/dashboard/org/$orgId/sessions/'
      preLoaderRoute: typeof DashboardOrgOrgIdSessionsIndexRouteImport
      parentRoute: typeof DashboardOrgOrgIdRoute
    }
    '/dashboard/org/$orgId/sessions/create': {
      id: '/dashboard/org/$orgId/sessions/create'
      path: '/sessions/create'
      fullPath: '/dashboard/org/$orgId/sessions/create'
      preLoaderRoute: typeof DashboardOrgOrgIdSessionsCreateRouteImport
      parentRoute: typeof DashboardOrgOrgIdRoute
    }
    '/dashboard/org/$orgId/sessions/$sessionId': {
      id: '/dashboard/org/$orgId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/dashboard/org/$orgId/sessions/$sessionId'
      preLoaderRoute: typeof DashboardOrgOrgIdSessionsSessionIdRouteImport
      parentRoute: typeof DashboardOrgOrgIdRoute
    }
    '/dashboard/org/$orgId/sessions/$sessionId/': {
      id: '/dashboard/org/$orgId/sessions/$sessionId/'
      path: '/'
      fullPath: '/dashboard/org/$orgId/sessions/$sessionId/'
      preLoaderRoute: typeof DashboardOrgOrgIdSessionsSessionIdIndexRouteImport
      parentRoute: typeof DashboardOrgOrgIdSessionsSessionIdRoute
    }
    '/dashboard/org/$orgId/sessions/$sessionId/roster': {
      id: '/dashboard/org/$orgId/sessions/$sessionId/roster'
      path: '/roster'
      fullPath: '/dashboard/org/$orgId/sessions/$sessionId/roster'
      preLoaderRoute: typeof DashboardOrgOrgIdSessionsSessionIdRosterRouteImport
      parentRoute: typeof DashboardOrgOrgIdSessionsSessionIdRoute
    }
    '/dashboard/org/$orgId/sessions/$sessionId/edit': {
      id: '/dashboard/org/$orgId/sessions/$sessionId/edit'
      path: '/edit'
      fullPath: '/dashboard/org/$orgId/sessions/$sessionId/edit'
      preLoaderRoute: typeof DashboardOrgOrgIdSessionsSessionIdEditRouteImport
      parentRoute: typeof DashboardOrgOrgIdSessionsSessionIdRoute
    }
  }
}

interface DashboardOrgOrgIdSessionsSessionIdRouteChildren {
  DashboardOrgOrgIdSessionsSessionIdEditRoute: typeof DashboardOrgOrgIdSessionsSessionIdEditRoute
  DashboardOrgOrgIdSessionsSessionIdRosterRoute: typeof DashboardOrgOrgIdSessionsSessionIdRosterRoute
  DashboardOrgOrgIdSessionsSessionIdIndexRoute: typeof DashboardOrgOrgIdSessionsSessionIdIndexRoute
}

const DashboardOrgOrgIdSessionsSessionIdRouteChildren: DashboardOrgOrgIdSessionsSessionIdRouteChildren =
  {
    DashboardOrgOrgIdSessionsSessionIdEditRoute:
      DashboardOrgOrgIdSessionsSessionIdEditRoute,
    DashboardOrgOrgIdSessionsSessionIdRosterRoute:
      DashboardOrgOrgIdSessionsSessionIdRosterRoute,
    DashboardOrgOrgIdSessionsSessionIdIndexRoute:
      DashboardOrgOrgIdSessionsSessionIdIndexRoute,
  }

const DashboardOrgOrgIdSessionsSessionIdRouteWithChildren =
  DashboardOrgOrgIdSessionsSessionIdRoute._addFileChildren(
    DashboardOrgOrgIdSessionsSessionIdRouteChildren,
  )

interface DashboardOrgOrgIdRouteChildren {
  DashboardOrgOrgIdInvitationsRoute: typeof DashboardOrgOrgIdInvitationsRoute
  DashboardOrgOrgIdJoinRequestsRoute: typeof DashboardOrgOrgIdJoinRequestsRoute
  DashboardOrgOrgIdMembersRoute: typeof DashboardOrgOrgIdMembersRoute
  DashboardOrgOrgIdProfileRoute: typeof DashboardOrgOrgIdProfileRoute
  DashboardOrgOrgIdSettingsRoute: typeof DashboardOrgOrgIdSettingsRoute
  DashboardOrgOrgIdIndexRoute: typeof DashboardOrgOrgIdIndexRoute
  DashboardOrgOrgIdSessionsSessionIdRoute: typeof DashboardOrgOrgIdSessionsSessionIdRouteWithChildren
  DashboardOrgOrgIdSessionsCreateRoute: typeof DashboardOrgOrgIdSessionsCreateRoute
  DashboardOrgOrgIdSessionsIndexRoute: typeof DashboardOrgOrgIdSessionsIndexRoute
}

const DashboardOrgOrgIdRouteChildren: DashboardOrgOrgIdRouteChildren = {
  DashboardOrgOrgIdInvitationsRoute: DashboardOrgOrgIdInvitationsRoute,
  DashboardOrgOrgIdJoinRequestsRoute: DashboardOrgOrgIdJoinRequestsRoute,
  DashboardOrgOrgIdMembersRoute: DashboardOrgOrgIdMembersRoute,
  DashboardOrgOrgIdProfileRoute: DashboardOrgOrgIdProfileRoute,
  DashboardOrgOrgIdSettingsRoute: DashboardOrgOrgIdSettingsRoute,
  DashboardOrgOrgIdIndexRoute: DashboardOrgOrgIdIndexRoute,
  DashboardOrgOrgIdSessionsSessionIdRoute:
    DashboardOrgOrgIdSessionsSessionIdRouteWithChildren,
  DashboardOrgOrgIdSessionsCreateRoute: DashboardOrgOrgIdSessionsCreateRoute,
  DashboardOrgOrgIdSessionsIndexRoute: DashboardOrgOrgIdSessionsIndexRoute,
}

const DashboardOrgOrgIdRouteWithChildren =
  DashboardOrgOrgIdRoute._addFileChildren(DashboardOrgOrgIdRouteChildren)

interface DashboardRouteChildren {
  DashboardInvitationsRoute: typeof DashboardInvitationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGroupsCreateRoute: typeof DashboardGroupsCreateRoute
  DashboardOrgOrgIdRoute: typeof DashboardOrgOrgIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInvitationsRoute: DashboardInvitationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGroupsCreateRoute: DashboardGroupsCreateRoute,
  DashboardOrgOrgIdRoute: DashboardOrgOrgIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  UsernameGroupSlugIndexRoute: UsernameGroupSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './global-middleware.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
